# document: https://github.com/realm/SwiftLint

identifier_name:
  min_length: # only min_length
    error: 2 # only error
  excluded: # excluded via string array
    - id
    - URL
    - x
    - y
    - vc
    - on
    - to
  reporter: "xcode"
